function [boost] = AttackBoost(lvl, attack)
% Requires heaviside(0) == 1
if heaviside(0) ~= 1
    sympref('HeavisideAtOrigin', 1);
end
nLvl = floor(lvl);
atk = floor(attack);
boost = ...
    (9+  0.04*atk)*heaviside(nLvl - 5) + ...
    (8 + 0.02*atk)*heaviside(nLvl - 4) - (8+.02*atk)*heaviside(nLvl - 5) + ...
    7*heaviside(nLvl - 3) - 7*heaviside(nLvl - 4) + ...
    5*heaviside(nLvl - 2) - 5*heaviside(nLvl - 3) + ...
    3*heaviside(nLvl - 1) - 3*heaviside(nLvl - 2);
end

